"use client";

import { useEffect, useMemo, useState } from "react";

type Drive = { dataName:string; friendlyName:string; driveClassification:string; requiredPowerPlant:string; thrust_N:number; EV_kps:number; flatMass_tons:number; specificPower_kgMW:number; efficiency:number; propellant:string; thrusters:number; perTankPropellantMaterials?:Record<string,number>; disable?:boolean };
type Family = "Chemical"|"Fission"|"Fusion"|"Antimatter"|"Electric"|"Other";
const COLORS:Record<Family,string>={Chemical:"#f4b942",Fission:"#65c79f",Fusion:"#a38cff",Antimatter:"#ff6f91",Electric:"#65b9ec",Other:"#a7b0b8"};
const SHAPES=["circle","diamond","square","triangle","cross"] as const;

function familyOf(d:Drive):Family { const v=d.driveClassification; if(v==="Chemical")return "Chemical"; if(v.includes("Fission")||v==="NuclearSaltWater")return "Fission"; if(v.includes("Fusion"))return "Fusion"; if(v==="Antimatter")return "Antimatter"; if(["Electrostatic","Electromagnetic","Electrothermal"].includes(v))return "Electric"; return "Other"; }
function readable(v:string){return v.replaceAll("_"," ").replace(/([a-z])([A-Z])/g,"$1 $2").replace(/\b\w/g,l=>l.toUpperCase())}
function subtypeKey(d:Drive){return d.requiredPowerPlant!=="Any_General"?d.requiredPowerPlant:d.driveClassification}
const SUBTYPE_LABELS:Record<string,string>={Antimatter_Beam_Core:"Antimatter beam core",Antimatter_Plasma_Core:"Antimatter plasma core",Chemical:"Chemical",Electromagnetic:"Electromagnetic",Electrostatic:"Electrostatic",Electrothermal:"Electrothermal",Fission_Pulse:"Fission pulse",Gas_Core_Fission:"Gas-core fission",Liquid_Core_Fission:"Liquid-core fission",NuclearSaltWater:"Nuclear salt water",Solid_Core_Fission:"Solid-core fission",Electrostatic_Confinement_Fusion:"Electrostatic fusion",Hybrid_Confinement_Fusion:"Hybrid fusion",Inertial_Confinement_Fusion:"Inertial fusion",Mirrored_Magnetic_Confinement_Fusion:"Mirror fusion",Toroid_Magnetic_Confinement_Fusion:"Torus fusion",Z_Pinch_Fusion:"Z-pinch fusion"};
function subtypeOf(d:Drive){const key=subtypeKey(d);return SUBTYPE_LABELS[key]??readable(key)}
function baseDriveName(d:Drive){return d.friendlyName.replace(/\s+x\d+$/i,"")}
function shapeOf(d:Drive){const t=`${d.driveClassification}:${d.requiredPowerPlant}`;let h=0;for(let i=0;i<t.length;i++)h=(h*31+t.charCodeAt(i))|0;return SHAPES[Math.abs(h)%SHAPES.length]}
function compact(v:number,u=""){return `${new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:2}).format(v)}${u}`}
function precise(v:number,u=""){return `${new Intl.NumberFormat("en",{maximumFractionDigits:2}).format(v)}${u}`}
function compositionOf(d:Drive){const entries=Object.entries(d.perTankPropellantMaterials??{}).filter(([,value])=>value>0);return entries.length?entries.map(([name,value])=>`${new Intl.NumberFormat("en",{maximumFractionDigits:1}).format(value*100)}% ${readable(name)}`).join(" · "):"No resource mix listed"}

function PropellantFilter({options,excluded,onToggle,onAll,onNone}:{options:string[];excluded:Set<string>;onToggle:(value:string)=>void;onAll:()=>void;onNone:()=>void}){
  const included=options.length-excluded.size;
  return <details className="filter-dropdown"><summary>{included===options.length?"All propellants":`${included} of ${options.length} propellants`}<span aria-hidden="true">⌄</span></summary><div className="filter-menu"><div className="filter-actions"><button type="button" onClick={onAll}>Select all</button><button type="button" onClick={onNone}>None</button></div>{options.map(option=><label className="filter-option" key={option}><input type="checkbox" checked={!excluded.has(option)} onChange={()=>onToggle(option)}/><span>{readable(option)}</span></label>)}</div></details>
}

function DriveTypeFilter({groups,excludedFamilies,excludedSubtypes,onFamily,onSubtype,onAll,onNone}:{groups:Array<{family:Family;subtypes:string[]}>;excludedFamilies:Set<Family>;excludedSubtypes:Set<string>;onFamily:(family:Family)=>void;onSubtype:(family:Family,subtype:string)=>void;onAll:()=>void;onNone:()=>void}){
  const familyCount=groups.filter(group=>!excludedFamilies.has(group.family)).length;
  const subtypeCount=groups.reduce((count,group)=>count+group.subtypes.filter(subtype=>!excludedFamilies.has(group.family)&&!excludedSubtypes.has(subtype)).length,0);
  const allSelected=familyCount===groups.length&&excludedSubtypes.size===0;
  return <details className="filter-dropdown type-dropdown"><summary>{allSelected?"All drive types":`${familyCount} families · ${subtypeCount} subtypes`}<span aria-hidden="true">⌄</span></summary><div className="filter-menu"><div className="filter-actions"><button type="button" onClick={onAll}>Select all</button><button type="button" onClick={onNone}>None</button></div>{groups.map(group=><div className={`filter-group${excludedFamilies.has(group.family)?" muted":""}`} key={group.family}><label className="filter-option family-option"><input type="checkbox" checked={!excludedFamilies.has(group.family)} onChange={()=>onFamily(group.family)}/><span className="legend-dot" style={{"--dot":COLORS[group.family]} as React.CSSProperties}/><strong>{group.family}</strong><small>{group.subtypes.filter(subtype=>!excludedSubtypes.has(subtype)).length}/{group.subtypes.length}</small></label><div className="subtype-options">{group.subtypes.map(subtype=><label className="filter-option" key={subtype}><input type="checkbox" checked={!excludedFamilies.has(group.family)&&!excludedSubtypes.has(subtype)} onChange={()=>onSubtype(group.family,subtype)}/><span>{SUBTYPE_LABELS[subtype]??readable(subtype)}</span></label>)}</div></div>)}</div></details>
}

function PlotShape({shape,x,y,color,selected}:{shape:typeof SHAPES[number];x:number;y:number;color:string;selected:boolean}){
  const p={fill:color,stroke:selected?"#fff":color,strokeWidth:selected?2:.7};
  if(shape==="diamond")return <rect x={x-3.5} y={y-3.5} width="7" height="7" rx=".8" transform={`rotate(45 ${x} ${y})`} {...p}/>;
  if(shape==="square")return <rect x={x-3.5} y={y-3.5} width="7" height="7" rx="1" {...p}/>;
  if(shape==="triangle")return <path d={`M ${x} ${y-4.5} L ${x+4.5} ${y+3.5} L ${x-4.5} ${y+3.5} Z`} {...p}/>;
  if(shape==="cross")return <path d={`M ${x-4} ${y-1.5} H ${x-1.5} V ${y-4} H ${x+1.5} V ${y-1.5} H ${x+4} V ${y+1.5} H ${x+1.5} V ${y+4} H ${x-1.5} V ${y+1.5} H ${x-4} Z`} {...p}/>;
  return <circle cx={x} cy={y} r={selected?4.5:3.5} {...p}/>;
}

export function DriveExplorer(){
  const [drives,setDrives]=useState<Drive[]>([]),[error,setError]=useState(""),[query,setQuery]=useState("");
  const [scale,setScale]=useState<"log"|"linear">("log"),[selected,setSelected]=useState<string[]>([]);
  const [maxOnly,setMaxOnly]=useState(true);
  const [showNames,setShowNames]=useState(false);
  const [readableText,setReadableText]=useState(false);
  const [excludedPropellants,setExcludedPropellants]=useState<Set<string>>(()=>new Set());
  const [excludedFamilies,setExcludedFamilies]=useState<Set<Family>>(()=>new Set());
  const [excludedSubtypes,setExcludedSubtypes]=useState<Set<string>>(()=>new Set());
  const [hovered,setHovered]=useState<{drive:Drive;x:number;y:number}|null>(null);
  useEffect(()=>{fetch("/data/TIDriveTemplate.json").then(r=>{if(!r.ok)throw new Error("Could not load the drive dataset.");return r.json()}).then((values:Drive[])=>{const active=values.filter(d=>!d.disable);setDrives(active);setSelected(["Apex Solid Rocket","Lars Drive","Triton Reflex Drive"].map(name=>active.filter(d=>baseDriveName(d)===name).sort((a,b)=>b.thrusters-a.thrusters)[0]?.dataName).filter((id):id is string=>Boolean(id)))}).catch(e=>setError(e instanceof Error?e.message:"Could not load data."))},[]);
  const propellantOptions=useMemo(()=>Array.from(new Set(drives.map(d=>d.propellant))).sort(),[drives]);
  const familyGroups=useMemo(()=>(Object.keys(COLORS) as Family[]).map(family=>({family,subtypes:Array.from(new Set(drives.filter(d=>familyOf(d)===family).map(subtypeKey))).sort()})).filter(group=>group.subtypes.length),[drives]);
  const filtered=useMemo(()=>{
    const candidates=maxOnly?Array.from(drives.reduce((groups,d)=>{const key=baseDriveName(d);const current=groups.get(key);if(!current||d.thrusters>current.thrusters)groups.set(key,d);return groups},new Map<string,Drive>()).values()):drives;
    const n=query.trim().toLowerCase();
    return candidates.filter(d=>!excludedPropellants.has(d.propellant)&&!excludedFamilies.has(familyOf(d))&&!excludedSubtypes.has(subtypeKey(d))&&(!n||`${d.friendlyName} ${d.driveClassification} ${d.requiredPowerPlant} ${d.propellant}`.toLowerCase().includes(n)))
  },[drives,excludedFamilies,excludedPropellants,excludedSubtypes,maxOnly,query]);
  const selectedDrives=selected.map(id=>drives.find(d=>d.dataName===id)).filter((d):d is Drive=>Boolean(d));
  const searchResults=query.trim()?filtered.slice(0,8):[];
  const chart={width:1400,height:760,left:88,right:34,top:34,bottom:70};
  const xs=filtered.map(d=>d.EV_kps).filter(v=>v>0),ys=filtered.map(d=>d.thrust_N).filter(v=>v>0);
  const domain={xMin:xs.length?Math.min(...xs):1,xMax:xs.length?Math.max(...xs):10,yMin:ys.length?Math.min(...ys):1,yMax:ys.length?Math.max(...ys):10};
  const norm=(v:number,min:number,max:number)=>scale==="log"?(Math.log10(v)-Math.log10(min))/Math.max(.00001,Math.log10(max)-Math.log10(min)):(v-min)/Math.max(.00001,max-min);
  const px=(v:number)=>chart.left+norm(v,domain.xMin,domain.xMax)*(chart.width-chart.left-chart.right),py=(v:number)=>chart.top+(1-norm(v,domain.yMin,domain.yMax))*(chart.height-chart.top-chart.bottom);
  const ticks=[0,.25,.5,.75,1],tickValue=(r:number,min:number,max:number)=>scale==="log"?10**(Math.log10(min)+r*(Math.log10(max)-Math.log10(min))):min+r*(max-min);
  const toggle=(id:string)=>setSelected(c=>c.includes(id)?c.filter(v=>v!==id):c.length<4?[...c,id]:c);
  const togglePropellant=(value:string)=>setExcludedPropellants(current=>{const next=new Set(current);if(next.has(value))next.delete(value);else next.add(value);return next});
  const toggleFamily=(value:Family)=>setExcludedFamilies(current=>{const next=new Set(current);if(next.has(value))next.delete(value);else next.add(value);return next});
  const toggleSubtype=(family:Family,value:string)=>{const familyWasExcluded=excludedFamilies.has(family);setExcludedSubtypes(current=>{const next=new Set(current);if(familyWasExcluded||next.has(value))next.delete(value);else next.add(value);return next});setExcludedFamilies(current=>{if(!current.has(family))return current;const next=new Set(current);next.delete(family);return next})};

  return <main className={`app-shell${readableText?" readable-text":""}`}>
    <header className="topbar"><div className="brand"><span className="brand-mark" aria-hidden="true"/>TI DRIVE COMPANION</div><div className="dataset-badge">Terra Invicta · {drives.length||"—"} active configurations</div></header>
    <section className="hero"><p className="eyebrow">Ship propulsion atlas / 01</p><h1>Find the drive that fits the mission.</h1><p>Map every drive by exhaust velocity and thrust, isolate a technology family, then pin up to four candidates for a direct performance readout.</p></section>
    <section className="workspace">
      <div className="panel"><div className="panel-head"><h2 className="panel-title">Performance envelope</h2><span className="count">{filtered.length} shown</span></div>
        <div className="accessibility-row"><label className="global-font-toggle"><input type="checkbox" checked={readableText} onChange={e=>setReadableText(e.target.checked)}/><span className="toggle-track" aria-hidden="true"><span/></span><span>Larger, clearer text</span></label></div>
        <div className="controls"><div className="search-control"><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, type, propellant…" aria-label="Search drives"/>{query&&<button className="clear-search" onClick={()=>setQuery("")} aria-label="Clear search filter" title="Clear search">×</button>}</div><PropellantFilter options={propellantOptions} excluded={excludedPropellants} onToggle={togglePropellant} onAll={()=>setExcludedPropellants(new Set())} onNone={()=>setExcludedPropellants(new Set(propellantOptions))}/><DriveTypeFilter groups={familyGroups} excludedFamilies={excludedFamilies} excludedSubtypes={excludedSubtypes} onFamily={toggleFamily} onSubtype={toggleSubtype} onAll={()=>{setExcludedFamilies(new Set());setExcludedSubtypes(new Set())}} onNone={()=>setExcludedFamilies(new Set(familyGroups.map(group=>group.family)))}/><label className="max-toggle"><input type="checkbox" checked={maxOnly} onChange={e=>setMaxOnly(e.target.checked)}/><span className="toggle-track" aria-hidden="true"><span/></span><span>Max thrusters only</span></label><label className="max-toggle"><input type="checkbox" checked={showNames} onChange={e=>setShowNames(e.target.checked)}/><span className="toggle-track" aria-hidden="true"><span/></span><span>Show drive names</span></label><div className="scale-toggle" aria-label="Chart scale"><button className={scale==="log"?"active":""} onClick={()=>setScale("log")} aria-pressed={scale==="log"}>Log</button><button className={scale==="linear"?"active":""} onClick={()=>setScale("linear")} aria-pressed={scale==="linear"}>Linear</button></div></div>
        <div className="legend">{(Object.keys(COLORS) as Family[]).map(n=><span className="legend-item" key={n}><span className="legend-dot" style={{"--dot":COLORS[n]} as React.CSSProperties}/>{n}</span>)}<span>• shape = power-plant subtype</span></div>
        {error?<div className="empty-state">{error}</div>:!drives.length?<div className="loading">Loading drive telemetry…</div>:!filtered.length?<div className="empty-state">No drives match the active filters.</div>:<div className="chart-wrap" onMouseLeave={()=>setHovered(null)}><svg className="chart" viewBox={`0 0 ${chart.width} ${chart.height}`} role="img" aria-label="Scatter plot of drive exhaust velocity versus thrust">
          {ticks.map(t=>{const x=chart.left+t*(chart.width-chart.left-chart.right),y=chart.top+(1-t)*(chart.height-chart.top-chart.bottom);return <g key={t}><line className="grid-line" x1={x} x2={x} y1={chart.top} y2={chart.height-chart.bottom}/><line className="grid-line" x1={chart.left} x2={chart.width-chart.right} y1={y} y2={y}/><text className="axis-text" x={x} y={chart.height-33} textAnchor="middle">{compact(tickValue(t,domain.xMin,domain.xMax))}</text><text className="axis-text" x={chart.left-10} y={y+3} textAnchor="end">{compact(tickValue(t,domain.yMin,domain.yMax))}</text></g>})}
          <text className="axis-label" x={(chart.left+chart.width-chart.right)/2} y={chart.height-7} textAnchor="middle">EXHAUST VELOCITY · KM/S</text><text className="axis-label" transform={`translate(15 ${(chart.top+chart.height-chart.bottom)/2}) rotate(-90)`} textAnchor="middle">THRUST · NEWTONS</text>
          {filtered.map(d=>{const x=px(d.EV_kps),y=py(d.thrust_N),active=selected.includes(d.dataName),labelOnLeft=x>chart.width-chart.right-180;return <g className={`point${active?" selected":""}`} style={{color:COLORS[familyOf(d)],opacity:active?1:.58}} key={d.dataName} onClick={()=>toggle(d.dataName)} onMouseEnter={()=>setHovered({drive:d,x:x/chart.width*100,y:y/chart.height*100})} onFocus={()=>setHovered({drive:d,x:x/chart.width*100,y:y/chart.height*100})} tabIndex={0} role="button" aria-label={`Compare ${d.friendlyName}`}><PlotShape shape={shapeOf(d)} x={x} y={y} color={COLORS[familyOf(d)]} selected={active}/>{showNames&&<text className="point-label" x={x+(labelOnLeft?-8:8)} y={y+3.5} textAnchor={labelOnLeft?"end":"start"}>{d.friendlyName}</text>}</g>})}
        </svg>{hovered&&<div className={`tooltip ${hovered.y>62?"above":"below"}`} style={{left:`${Math.min(hovered.x,72)}%`,...(hovered.y>62?{bottom:`${100-Math.max(10,Math.min(hovered.y,88))}%`}:{top:`${Math.max(10,Math.min(hovered.y,88))}%`})}}><strong>{hovered.drive.friendlyName}</strong><div className="tooltip-grid"><span>Thrust</span><span>{compact(hovered.drive.thrust_N," N")}</span><span>Exhaust</span><span>{precise(hovered.drive.EV_kps," km/s")}</span><span>Subtype</span><span>{subtypeOf(hovered.drive)}</span><span>Propellant</span><span>{readable(hovered.drive.propellant)}</span></div><div className="tooltip-materials"><span>Tank composition</span><b>{compositionOf(hovered.drive)}</b></div></div>}</div>}
      </div>
      <aside className="panel compare-panel"><div className="panel-head"><h2 className="panel-title">Compare</h2><span className="count">{selected.length} / 4</span></div><p className="compare-help">Click a point or search by name and type. Shapes distinguish power-plant subtypes inside each color family.</p>
        {searchResults.length>0&&<div className="results">{searchResults.map(d=><div className="result-row" key={d.dataName}><div><div className="result-name">{d.friendlyName}</div><div className="result-meta">{familyOf(d)} · {subtypeOf(d)}</div></div><button className="add-btn" disabled={selected.length>=4&&!selected.includes(d.dataName)} onClick={()=>toggle(d.dataName)} aria-label={`${selected.includes(d.dataName)?"Remove":"Add"} ${d.friendlyName}`}>{selected.includes(d.dataName)?"−":"+"}</button></div>)}</div>}
        <div className="compare-list">{selectedDrives.length?selectedDrives.map(d=>{const color=COLORS[familyOf(d)];return <article className="drive-card" key={d.dataName}><div className="drive-card-head"><span className={`glyph ${shapeOf(d)}`} style={{"--glyph":color} as React.CSSProperties}/><div><h3>{d.friendlyName}</h3><div className="subtype">{familyOf(d)} · {subtypeOf(d)}</div></div><button className="remove-btn" onClick={()=>toggle(d.dataName)} aria-label={`Remove ${d.friendlyName}`}>×</button></div><div className="metrics"><div className="metric"><div className="metric-label">Thrust</div><div className="metric-value">{compact(d.thrust_N," N")}</div></div><div className="metric"><div className="metric-label">Exhaust velocity</div><div className="metric-value">{precise(d.EV_kps," km/s")}</div></div><div className="metric"><div className="metric-label">Drive mass</div><div className="metric-value">{precise(d.flatMass_tons," t")}</div></div><div className="metric"><div className="metric-label">Propellant</div><div className="metric-value">{readable(d.propellant)}</div></div><div className="metric metric-wide"><div className="metric-label">Tank composition</div><div className="metric-value">{compositionOf(d)}</div></div></div></article>}):<div className="no-selection">Choose drives from the chart to build a comparison.</div>}</div><p className="footer-note">Data loaded at runtime from TIDriveTemplate.json. Disabled configurations are hidden.</p>
      </aside>
    </section>
  </main>
}
